language: cpp

compiler:
  - gcc

sudo: required
dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential qt5-default qttools5-dev-tools qttools5-dev

script:
  - cd snapcraft-qt
  - qmake -r
  - make
  - make check

notifications:
  email: false
