name: snapcraft-gui  # the name of the snap
version:  "daily"  # the version of the snap
summary: Build and manage snaps on Ubuntu Linux  # 79 char long summary
description: Frontend for snapcraft which help build and manage snaps on Ubuntu Linux  # a longer description for the snap
confinement: strict  # use "strict" to enforce system access only via declared interfaces

apps:
    snapcraft-gui: 
         command:  desktop-launch  snapcraft-gui
         plugs:
               - unity7
               - network
               - network-bind
               - home
               - mount-observe
               - opengl
               - x11
          after: [desktop-qt5]
parts:
    snapcraft-gui: 
        source: lp:snpacraft-gui
        source-type: bzr
        plugin: nil

env:
        plugin: nil
        stage-packages:
               - tree
               - pastebinit